package com.sample
 
import com.sample.DroolsTest.Message;
 
rule "Hello"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end

rule "a message exists" 
	when
		m:Message()
	then
		System.out.println( "I found a message with a message of " + m.getMessage() );
end

		
